IF Object_Id('src.grady_substanceuse') IS NOT NULL
    DROP TABLE src.grady_substanceuse
GO

CREATE TABLE src.grady_substanceuse (
    icd_concept_name VARCHAR(255)
    , icd_code VARCHAR(20)
);
PRINT 'Table src.grady_substanceuse created.'
GO

INSERT INTO src.grady_substanceuse
(
    icd_concept_name
    , icd_code
)
VALUES
('Cannabis dependence with psychotic disorder with delusions', 'F12.250')
, ('Cannabis dependence with psychotic disorder with hallucinations', 'F12.251')
, ('Cannabis dependence with psychotic disorder, unspecified', 'F12.259')
, ('Cannabis dependence with other cannabis-induced disorder', 'F12.28')
, ('Cannabis dependence with cannabis-induced anxiety disorder', 'F12.280')
, ('Cannabis dependence with other cannabis-induced disorder', 'F12.288')
, ('Cannabis dependence with unspecified cannabis-induced disorder', 'F12.29')
, ('Cannabis use, unspecified', 'F12.9')
, ('Cannabis use, unspecified with intoxication', 'F12.92')
, ('Cannabis use, unspecified with intoxication, uncomplicated', 'F12.920')
, ('Cannabis use, unspecified with intoxication delirium', 'F12.921')
, ('Cannabis use, unspecified with intoxication with perceptual disturbance', 'F12.922')
, ('Cannabis use, unspecified with intoxication, unspecified', 'F12.929')
, ('Cannabis use, unspecified with withdrawal', 'F12.93')
, ('Cannabis use, unspecified with psychotic disorder', 'F12.95')
, ('Cannabis use, unspecified with psychotic disorder with delusions', 'F12.950')
, ('Cannabis use, unspecified with psychotic disorder with hallucinations', 'F12.951')
, ('Cannabis use, unspecified with psychotic disorder, unspecified', 'F12.959')
, ('Cannabis use, unspecified with other cannabis-induced disorder', 'F12.98')
, ('Cannabis use, unspecified with anxiety disorder', 'F12.980')
, ('Cannabis use, unspecified with other cannabis-induced disorder', 'F12.988')
, ('Cannabis use, unspecified with unspecified cannabis-induced disorder', 'F12.99')
, ('Sedative, hypnotic, or anxiolytic related disorders', 'F13')
, ('Sedative, hypnotic or anxiolytic-related abuse', 'F13.1')
, ('Sedative, hypnotic or anxiolytic abuse, uncomplicated', 'F13.10')
, ('Sedative, hypnotic or anxiolytic abuse with intoxication', 'F13.12')
, ('Sedative, hypnotic or anxiolytic abuse with intoxication, uncomplicated', 'F13.120')
, ('Sedative, hypnotic or anxiolytic abuse with intoxication delirium', 'F13.121')
, ('Sedative, hypnotic or anxiolytic abuse with intoxication, unspecified', 'F13.129')
, ('Sedative, hypnotic or anxiolytic abuse with withdrawal', 'F13.13')
, ('Sedative, hypnotic or anxiolytic abuse with withdrawal, uncomplicated', 'F13.130')
, ('Sedative, hypnotic or anxiolytic abuse with withdrawal, uncomplicated', 'F13.130')
, ('Sedative, hypnotic or anxiolytic abuse with withdrawal delirium', 'F13.131')
, ('Sedative, hypnotic or anxiolytic abuse with withdrawal with perceptual disturbance', 'F13.132')
, ('Sedative, hypnotic or anxiolytic abuse with withdrawal, unspecified', 'F13.139')
, ('Sedative, hypnotic or anxiolytic abuse with sedative, hypnotic or anxiolytic-induced mood disorder', 'F13.14')
, ('Sedative, hypnotic or anxiolytic abuse with sedative, hypnotic or anxiolytic-induced psychotic disorder', 'F13.15')
, ('Sedative, hypnotic or anxiolytic abuse with sedative, hypnotic or anxiolytic-induced psychotic disorder with delusions', 'F13.150')
, ('Sedative, hypnotic or anxiolytic abuse with sedative, hypnotic or anxiolytic-induced psychotic disorder with hallucinations', 'F13.151')
, ('Sedative, hypnotic or anxiolytic abuse with sedative, hypnotic or anxiolytic-induced psychotic disorder, unspecified', 'F13.159')
, ('Sedative, hypnotic or anxiolytic abuse with other sedative, hypnotic or anxiolytic-induced disorders', 'F13.18')
, ('Sedative, hypnotic or anxiolytic abuse with sedative, hypnotic or anxiolytic-induced anxiety disorder', 'F13.180')
, ('Sedative, hypnotic or anxiolytic abuse with sedative, hypnotic or anxiolytic-induced sexual dysfunction', 'F13.181')
, ('Sedative, hypnotic or anxiolytic abuse with sedative, hypnotic or anxiolytic-induced sleep disorder', 'F13.182')
, ('Sedative, hypnotic or anxiolytic abuse with other sedative, hypnotic or anxiolytic-induced disorder', 'F13.188')
, ('Sedative, hypnotic or anxiolytic abuse with unspecified sedative, hypnotic or anxiolytic-induced disorder', 'F13.19')
, ('Sedative, hypnotic or anxiolytic-related dependence', 'F13.2')
, ('Sedative, hypnotic or anxiolytic dependence, uncomplicated', 'F13.20')
, ('Sedative, hypnotic or anxiolytic dependence with intoxication', 'F13.22')
, ('Sedative, hypnotic or anxiolytic dependence with intoxication, uncomplicated', 'F13.220')
, ('Sedative, hypnotic or anxiolytic dependence with intoxication delirium', 'F13.221')
, ('Sedative, hypnotic or anxiolytic dependence with intoxication, unspecified', 'F13.229')
, ('Sedative, hypnotic or anxiolytic dependence with withdrawal', 'F13.23')
, ('Sedative, hypnotic or anxiolytic dependence with withdrawal, uncomplicated', 'F13.230')
, ('Sedative, hypnotic or anxiolytic dependence with withdrawal delirium', 'F13.231')
, ('Sedative, hypnotic or anxiolytic dependence with withdrawal with perceptual disturbance', 'F13.232')
, ('Sedative, hypnotic or anxiolytic dependence with withdrawal, unspecified', 'F13.239')
, ('Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced mood disorder', 'F13.24')
, ('Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced psychotic disorder', 'F13.25')
, ('Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced psychotic disorder with delusions', 'F13.250')
, ('Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced psychotic disorder with hallucinations', 'F13.251')
, ('Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced psychotic disorder, unspecified', 'F13.259')
, ('Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced persisting amnestic disorder', 'F13.26')
, ('Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced persisting dementia', 'F13.27')
, ('Sedative, hypnotic or anxiolytic dependence with other sedative, hypnotic or anxiolytic-induced disorders', 'F13.28')
, ('Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced anxiety disorder', 'F13.280')
, ('Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced sexual dysfunction', 'F13.281')
, ('Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced sleep disorder', 'F13.282')
, ('Sedative, hypnotic or anxiolytic dependence with other sedative, hypnotic or anxiolytic-induced disorder', 'F13.288')
, ('Sedative, hypnotic or anxiolytic dependence with unspecified sedative, hypnotic or anxiolytic-induced disorder', 'F13.29')
, ('Sedative, hypnotic or anxiolytic-related use, unspecified', 'F13.9')
, ('Sedative, hypnotic or anxiolytic use, unspecified with intoxication', 'F13.92')
, ('Sedative, hypnotic or anxiolytic use, unspecified with intoxication, uncomplicated', 'F13.920')
, ('Sedative, hypnotic or anxiolytic use, unspecified with intoxication delirium', 'F13.921')
, ('Sedative, hypnotic or anxiolytic use, unspecified with intoxication, unspecified', 'F13.929')
, ('Sedative, hypnotic or anxiolytic use, unspecified with withdrawal', 'F13.93')
, ('Sedative, hypnotic or anxiolytic use, unspecified with withdrawal, uncomplicated', 'F13.930')
, ('Sedative, hypnotic or anxiolytic use, unspecified with withdrawal delirium', 'F13.931')
, ('Sedative, hypnotic or anxiolytic use, unspecified with withdrawal with perceptual disturbances', 'F13.932')
, ('Sedative, hypnotic or anxiolytic use, unspecified with withdrawal, unspecified', 'F13.939')
, ('Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced mood disorder', 'F13.94')
, ('Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced psychotic disorder', 'F13.95')
, ('Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced psychotic disorder with delusions', 'F13.950')
, ('Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced psychotic disorder with hallucinations', 'F13.951')
, ('Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced psychotic disorder, unspecified', 'F13.959')
, ('Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced persisting amnestic disorder', 'F13.96')
, ('Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced persisting dementia', 'F13.97')
, ('Sedative, hypnotic or anxiolytic use, unspecified with other sedative, hypnotic or anxiolytic-induced disorders', 'F13.98')
, ('Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced anxiety disorder', 'F13.980')
, ('Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced sexual dysfunction', 'F13.981')
, ('Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced sleep disorder', 'F13.982')
, ('Sedative, hypnotic or anxiolytic use, unspecified with other sedative, hypnotic or anxiolytic-induced disorder', 'F13.988')
, ('Sedative, hypnotic or anxiolytic use, unspecified with unspecified sedative, hypnotic or anxiolytic-induced disorder', 'F13.99')
, ('Cocaine related disorders', 'F14')
, ('Cocaine abuse', 'F14.1')
, ('Cocaine abuse, uncomplicated', 'F14.10')
, ('Cocaine abuse with intoxication', 'F14.12')
, ('Cocaine abuse with intoxication, uncomplicated', 'F14.120')
, ('Cocaine abuse with intoxication with delirium', 'F14.121')
, ('Cocaine abuse with intoxication with perceptual disturbance', 'F14.122')
, ('Cocaine abuse with intoxication, unspecified', 'F14.129')
, ('Cocaine abuse, unspecified with withdrawal', 'F14.13')
, ('Cocaine abuse with cocaine-induced mood disorder', 'F14.14')
, ('Cocaine abuse with cocaine-induced psychotic disorder', 'F14.15')
, ('Cocaine abuse with cocaine-induced psychotic disorder with delusions', 'F14.150')
, ('Cocaine abuse with cocaine-induced psychotic disorder with hallucinations', 'F14.151')
, ('Cocaine abuse with cocaine-induced psychotic disorder, unspecified', 'F14.159')
, ('Cocaine abuse with other cocaine-induced disorder', 'F14.18')
, ('Cocaine abuse with cocaine-induced anxiety disorder', 'F14.180')
, ('Cocaine abuse with cocaine-induced sexual dysfunction', 'F14.181')
, ('Cocaine abuse with cocaine-induced sleep disorder', 'F14.182')
, ('Cocaine abuse with other cocaine-induced disorder', 'F14.188')
, ('Cocaine abuse with unspecified cocaine-induced disorder', 'F14.19')
, ('Cocaine dependence', 'F14.2')
, ('Cocaine dependence, uncomplicated', 'F14.20')
, ('Cocaine dependence with intoxication', 'F14.22')
, ('Cocaine dependence with intoxication, uncomplicated', 'F14.220')
, ('Cocaine dependence with intoxication delirium', 'F14.221')
, ('Cocaine dependence with intoxication with perceptual disturbance', 'F14.222')
, ('Cocaine dependence with intoxication, unspecified', 'F14.229')
, ('Cocaine dependence with withdrawal', 'F14.23')
, ('Cocaine dependence with cocaine-induced mood disorder', 'F14.24')
, ('Cocaine dependence with cocaine-induced psychotic disorder', 'F14.25')
, ('Cocaine dependence with cocaine-induced psychotic disorder with delusions', 'F14.250')
, ('Cocaine dependence with cocaine-induced psychotic disorder with hallucinations', 'F14.251')
, ('Cocaine dependence with cocaine-induced psychotic disorder, unspecified', 'F14.259')
, ('Cocaine dependence with other cocaine-induced disorder', 'F14.28')
, ('Cocaine dependence with cocaine-induced anxiety disorder', 'F14.280')
, ('Cocaine dependence with cocaine-induced sexual dysfunction', 'F14.281')
, ('Cocaine dependence with cocaine-induced sleep disorder', 'F14.282')
, ('Cocaine dependence with other cocaine-induced disorder', 'F14.288')
, ('Cocaine dependence with unspecified cocaine-induced disorder', 'F14.29')
, ('Cocaine use, unspecified', 'F14.9')
, ('Cocaine use, unspecified, uncomplicated', 'F14.90')
, ('Cocaine use, unspecified with intoxication', 'F14.92')
, ('Cocaine use, unspecified with intoxication, uncomplicated', 'F14.920')
, ('Cocaine use, unspecified with intoxication delirium', 'F14.921')
, ('Cocaine use, unspecified with intoxication with perceptual disturbance', 'F14.922')
, ('Cocaine use, unspecified with intoxication, unspecified', 'F14.929')
, ('Cocaine use, unspecified with withdrawal', 'F14.93')
, ('Cocaine use, unspecified with cocaine-induced mood disorder', 'F14.94')
, ('Cocaine use, unspecified with cocaine-induced psychotic disorder', 'F14.95')
, ('Cocaine use, unspecified with cocaine-induced psychotic disorder with delusions', 'F14.950')
, ('Cocaine use, unspecified with cocaine-induced psychotic disorder with hallucinations', 'F14.951')
, ('Cocaine use, unspecified with cocaine-induced psychotic disorder, unspecified', 'F14.959')
, ('Cocaine use, unspecified with other specified cocaine-induced disorder', 'F14.98')
, ('Cocaine use, unspecified with cocaine-induced anxiety disorder', 'F14.980')
, ('Cocaine use, unspecified with cocaine-induced sexual dysfunction', 'F14.981')
, ('Cocaine use, unspecified with cocaine-induced sleep disorder', 'F14.982')
, ('Cocaine use, unspecified with other cocaine-induced disorder', 'F14.988')
, ('Cocaine use, unspecified with unspecified cocaine-induced disorder', 'F14.99')
, ('Other stimulant related disorders', 'F15')
, ('Other stimulant abuse', 'F15.1')
, ('Other stimulant abuse, uncomplicated', 'F15.10')
, ('Other stimulant abuse with intoxication', 'F15.12')
, ('Other stimulant abuse with intoxication, uncomplicated', 'F15.120')
, ('Other stimulant abuse with intoxication delirium', 'F15.121')
, ('Other stimulant abuse with intoxication with perceptual disturbance', 'F15.122')
, ('Other stimulant abuse with intoxication, unspecified', 'F15.129')
, ('Other stimulant abuse with withdrawal', 'F15.13')
, ('Other stimulant abuse with stimulant-induced mood disorder', 'F15.14')
, ('Other stimulant abuse with stimulant-induced psychotic disorder', 'F15.15')
, ('Other stimulant abuse with stimulant-induced psychotic disorder with delusions', 'F15.150')
, ('Other stimulant abuse with stimulant-induced psychotic disorder with hallucinations', 'F15.151')
, ('Other stimulant abuse with stimulant-induced psychotic disorder, unspecified', 'F15.159')
, ('Other stimulant abuse with other stimulant-induced disorder', 'F15.18')
, ('Other stimulant abuse with stimulant-induced anxiety disorder', 'F15.180')
, ('Other stimulant abuse with stimulant-induced sexual dysfunction', 'F15.181')
, ('Other stimulant abuse with stimulant-induced sleep disorder', 'F15.182')
, ('Other stimulant abuse with other stimulant-induced disorder', 'F15.188')
, ('Other stimulant abuse with unspecified stimulant-induced disorder', 'F15.19')
, ('Other stimulant dependence', 'F15.2')
, ('Other stimulant dependence, uncomplicated', 'F15.20')
, ('Other stimulant dependence with intoxication', 'F15.22')
, ('Other stimulant dependence with intoxication, uncomplicated', 'F15.220')
, ('Other stimulant dependence with intoxication delirium', 'F15.221')
, ('Other stimulant dependence with intoxication with perceptual disturbance', 'F15.222')
, ('Other stimulant dependence with intoxication, unspecified', 'F15.229')
, ('Other stimulant dependence with withdrawal', 'F15.23')
, ('Other stimulant dependence with stimulant-induced mood disorder', 'F15.24')
, ('Other stimulant dependence with stimulant-induced psychotic disorder', 'F15.25')
, ('Other stimulant dependence with stimulant-induced psychotic disorder with delusions', 'F15.250')
, ('Other stimulant dependence with stimulant-induced psychotic disorder with hallucinations', 'F15.251')
, ('Other stimulant dependence with stimulant-induced psychotic disorder, unspecified', 'F15.259')
, ('Other stimulant dependence with other stimulant-induced disorder', 'F15.28')
, ('Other stimulant dependence with stimulant-induced anxiety disorder', 'F15.280')
, ('Other stimulant dependence with stimulant-induced sexual dysfunction', 'F15.281')
, ('Other stimulant dependence with stimulant-induced sleep disorder', 'F15.282')
, ('Other stimulant dependence with other stimulant-induced disorder', 'F15.288')
, ('Other stimulant dependence with unspecified stimulant-induced disorder', 'F15.29')
, ('Other stimulant use, unspecified', 'F15.9')
, ('Other stimulant use, unspecified, uncomplicated', 'F15.90')
, ('Other stimulant use, unspecified with intoxication', 'F15.92')
, ('Other stimulant use, unspecified with intoxication, uncomplicated', 'F15.920')
, ('Other stimulant use, unspecified with intoxication delirium', 'F15.921')
, ('Other stimulant use, unspecified with intoxication with perceptual disturbance', 'F15.922')
, ('Other stimulant use, unspecified with intoxication, unspecified', 'F15.929')
, ('Other stimulant use, unspecified with withdrawal', 'F15.93')
, ('Other stimulant use, unspecified with stimulant-induced mood disorder', 'F15.94')
, ('Other stimulant use, unspecified with stimulant-induced psychotic disorder', 'F15.95')
, ('Other stimulant use, unspecified with stimulant-induced psychotic disorder with delusions', 'F15.950')
, ('Other stimulant use, unspecified with stimulant-induced psychotic disorder with hallucinations', 'F15.951')
, ('Other stimulant use, unspecified with stimulant-induced psychotic disorder, unspecified', 'F15.959')
, ('Other stimulant use, unspecified with other stimulant-induced disorder', 'F15.98')
, ('Other stimulant use, unspecified with stimulant-induced anxiety disorder', 'F15.980')
, ('Other stimulant use, unspecified with stimulant-induced sexual dysfunction', 'F15.981')
, ('Other stimulant use, unspecified with stimulant-induced sleep disorder', 'F15.982')
, ('Other stimulant use, unspecified with other stimulant-induced disorder', 'F15.988')
, ('Other stimulant use, unspecified with unspecified stimulant-induced disorder', 'F15.99')
, ('Hallucinogen related disorders', 'F16')
, ('Hallucinogen abuse', 'F16.1')
, ('Hallucinogen abuse, uncomplicated', 'F16.10')
, ('Hallucinogen abuse with intoxication', 'F16.12')
, ('Hallucinogen abuse with intoxication, uncomplicated', 'F16.120')
, ('Hallucinogen abuse with intoxication with delirium', 'F16.121')
, ('Hallucinogen abuse with intoxication with perceptual disturbance', 'F16.122')
, ('Hallucinogen abuse with intoxication, unspecified', 'F16.129')
, ('Hallucinogen abuse with hallucinogen-induced mood disorder', 'F16.14')
, ('Hallucinogen abuse with hallucinogen-induced psychotic disorder', 'F16.15')
, ('Hallucinogen abuse with hallucinogen-induced psychotic disorder with delusions', 'F16.150')
, ('Hallucinogen abuse with hallucinogen-induced psychotic disorder with hallucinations', 'F16.151')
, ('Hallucinogen abuse with hallucinogen-induced psychotic disorder, unspecified', 'F16.159')
, ('Hallucinogen abuse with other hallucinogen-induced disorder', 'F16.18')
, ('Hallucinogen abuse with hallucinogen-induced anxiety disorder', 'F16.180')
, ('Hallucinogen abuse with hallucinogen persisting perception disorder (flashbacks)', 'F16.183')
, ('Hallucinogen abuse with other hallucinogen-induced disorder', 'F16.188')
, ('Hallucinogen abuse with unspecified hallucinogen-induced disorder', 'F16.19')
, ('Hallucinogen dependence', 'F16.2')
, ('Hallucinogen dependence, uncomplicated', 'F16.20')
, ('Hallucinogen dependence with intoxication', 'F16.22')
, ('Hallucinogen dependence with intoxication, uncomplicated', 'F16.220')
, ('Hallucinogen dependence with intoxication with delirium', 'F16.221')
, ('Hallucinogen dependence with intoxication, unspecified', 'F16.229')
, ('Hallucinogen dependence with hallucinogen-induced mood disorder', 'F16.24')
, ('Hallucinogen dependence with hallucinogen-induced psychotic disorder', 'F16.25')
, ('Hallucinogen dependence with hallucinogen-induced psychotic disorder with delusions', 'F16.250')
, ('Hallucinogen dependence with hallucinogen-induced psychotic disorder with hallucinations', 'F16.251')
, ('Hallucinogen dependence with hallucinogen-induced psychotic disorder, unspecified', 'F16.259')
, ('Hallucinogen dependence with other hallucinogen-induced disorder', 'F16.28')
, ('Hallucinogen dependence with hallucinogen-induced anxiety disorder', 'F16.280')
, ('Hallucinogen dependence with hallucinogen persisting perception disorder (flashbacks)', 'F16.283')
, ('Hallucinogen dependence with other hallucinogen-induced disorder', 'F16.288')
, ('Hallucinogen dependence with unspecified hallucinogen-induced disorder', 'F16.29')
, ('Hallucinogen use, unspecified', 'F16.9')
, ('Hallucinogen use, unspecified, uncomplicated', 'F16.90')
, ('Hallucinogen use, unspecified with intoxication', 'F16.92')
, ('Hallucinogen use, unspecified with intoxication, uncomplicated', 'F16.920')
, ('Hallucinogen use, unspecified with intoxication with delirium', 'F16.921')
, ('Hallucinogen use, unspecified with intoxication, unspecified', 'F16.929')
, ('Hallucinogen use, unspecified with hallucinogen-induced mood disorder', 'F16.94')
, ('Hallucinogen use, unspecified with hallucinogen-induced psychotic disorder', 'F16.95')
, ('Hallucinogen use, unspecified with hallucinogen-induced psychotic disorder with delusions', 'F16.950')
, ('Hallucinogen use, unspecified with hallucinogen-induced psychotic disorder with hallucinations', 'F16.951')
, ('Hallucinogen use, unspecified with hallucinogen-induced psychotic disorder, unspecified', 'F16.959')
, ('Hallucinogen use, unspecified with other specified hallucinogen-induced disorder', 'F16.98')
, ('Hallucinogen use, unspecified with hallucinogen-induced anxiety disorder', 'F16.980')
, ('Hallucinogen use, unspecified with hallucinogen persisting perception disorder (flashbacks)', 'F16.983')
, ('Hallucinogen use, unspecified with other hallucinogen-induced disorder', 'F16.988')
, ('Hallucinogen use, unspecified with unspecified hallucinogen-induced disorder', 'F16.99')
, ('Inhalant related disorders', 'F18')
, ('Inhalant abuse', 'F18.1')
, ('Inhalant abuse, uncomplicated', 'F18.10')
, ('Inhalant abuse with intoxication', 'F18.12')
, ('Inhalant abuse with intoxication, uncomplicated', 'F18.120')
, ('Inhalant abuse with intoxication delirium', 'F18.121')
, ('Inhalant abuse with intoxication, unspecified', 'F18.129')
, ('Inhalant abuse with inhalant-induced mood disorder', 'F18.14')
, ('Inhalant abuse with inhalant-induced psychotic disorder', 'F18.15')
, ('Inhalant abuse with inhalant-induced psychotic disorder with delusions', 'F18.150')
, ('Inhalant abuse with inhalant-induced psychotic disorder with hallucinations', 'F18.151')
, ('Inhalant abuse with inhalant-induced psychotic disorder with hallucinations', 'F18.151')
, ('Inhalant abuse with inhalant-induced psychotic disorder, unspecified', 'F18.159')
, ('Inhalant abuse with inhalant-induced dementia', 'F18.17')
, ('Inhalant abuse with other inhalant-induced disorders', 'F18.18')
, ('Inhalant abuse with inhalant-induced anxiety disorder', 'F18.180')
, ('Inhalant abuse with other inhalant-induced disorder', 'F18.188')
, ('Inhalant abuse with unspecified inhalant-induced disorder', 'F18.19')
, ('Inhalant dependence', 'F18.2')
, ('Inhalant dependence, uncomplicated', 'F18.20')
, ('Inhalant dependence with intoxication', 'F18.22')
, ('Inhalant dependence with intoxication, uncomplicated', 'F18.220')
, ('Inhalant dependence with intoxication delirium', 'F18.221')
, ('Inhalant dependence with intoxication, unspecified', 'F18.229')
, ('Inhalant dependence with inhalant-induced mood disorder', 'F18.24')
, ('Inhalant dependence with inhalant-induced psychotic disorder', 'F18.25')
, ('Inhalant dependence with inhalant-induced psychotic disorder with delusions', 'F18.250')
, ('Inhalant dependence with inhalant-induced psychotic disorder with hallucinations', 'F18.251')
, ('Inhalant dependence with inhalant-induced psychotic disorder, unspecified', 'F18.259')
, ('Inhalant dependence with inhalant-induced dementia', 'F18.27')
, ('Inhalant dependence with other inhalant-induced disorders', 'F18.28')
, ('Inhalant dependence with inhalant-induced anxiety disorder', 'F18.280')
, ('Inhalant dependence with other inhalant-induced disorder', 'F18.288')
, ('Inhalant dependence with unspecified inhalant-induced disorder', 'F18.29')
, ('Inhalant use, unspecified', 'F18.9')
, ('Inhalant use, unspecified, uncomplicated', 'F18.90')
, ('Inhalant use, unspecified, in remission', 'F18.91')
, ('Inhalant use, unspecified with intoxication', 'F18.92')
, ('Inhalant use, unspecified with intoxication, uncomplicated', 'F18.920')
, ('Inhalant use, unspecified with intoxication with delirium', 'F18.921')
, ('Inhalant use, unspecified with intoxication, unspecified', 'F18.929')
, ('Inhalant use, unspecified with inhalant-induced mood disorder', 'F18.94')
, ('Inhalant use, unspecified with inhalant-induced psychotic disorder', 'F18.95')
, ('Inhalant use, unspecified with inhalant-induced psychotic disorder with delusions', 'F18.950')
, ('Inhalant use, unspecified with inhalant-induced psychotic disorder with hallucinations', 'F18.951')
, ('Inhalant use, unspecified with inhalant-induced psychotic disorder, unspecified', 'F18.959')
, ('Inhalant use, unspecified with inhalant-induced persisting dementia', 'F18.97')
, ('Inhalant use, unspecified with other inhalant-induced disorders', 'F18.98')
, ('Inhalant use, unspecified with inhalant-induced anxiety disorder', 'F18.980')
, ('Inhalant use, unspecified with other inhalant-induced disorder', 'F18.988')
, ('Inhalant use, unspecified with unspecified inhalant-induced disorder', 'F18.99')
, ('Other psychoactive substance related disorders', 'F19')
, ('Other psychoactive substance abuse', 'F19.1')
, ('Other psychoactive substance abuse, uncomplicated', 'F19.10')
, ('Other psychoactive substance abuse with intoxication', 'F19.12')
, ('Other psychoactive substance abuse with intoxication, uncomplicated', 'F19.120')
, ('Other psychoactive substance abuse with intoxication delirium', 'F19.121')
, ('Other psychoactive substance abuse with intoxication with perceptual disturbances', 'F19.122')
, ('Other psychoactive substance abuse with intoxication, unspecified', 'F19.129')
, ('Other psychoactive substance abuse with withdrawal', 'F19.13')
, ('Other psychoactive substance abuse with withdrawal, uncomplicated', 'F19.130')
, ('Other psychoactive substance abuse with withdrawal delirium', 'F19.131')
, ('Other psychoactive substance abuse with withdrawal with perceptual disturbance', 'F19.132')
, ('Other psychoactive substance abuse with withdrawal, unspecified', 'F19.139')
, ('Other psychoactive substance abuse with psychoactive substance-induced mood disorder', 'F19.14')
, ('Other psychoactive substance abuse with psychoactive substance-induced psychotic disorder', 'F19.15')
, ('Other psychoactive substance abuse with psychoactive substance-induced psychotic disorder with delusions', 'F19.150')
, ('Other psychoactive substance abuse with psychoactive substance-induced psychotic disorder with hallucinations', 'F19.151')
, ('Other psychoactive substance abuse with psychoactive substance-induced psychotic disorder, unspecified', 'F19.159')
, ('Other psychoactive substance abuse with psychoactive substance-induced persisting amnestic disorder', 'F19.16')
, ('Other psychoactive substance abuse with psychoactive substance-induced persisting dementia', 'F19.17')
, ('Other psychoactive substance abuse with other psychoactive substance-induced disorders', 'F19.18')
, ('Other psychoactive substance abuse with psychoactive substance-induced anxiety disorder', 'F19.180')
, ('Other psychoactive substance abuse with psychoactive substance-induced sexual dysfunction', 'F19.181')
, ('Other psychoactive substance abuse with psychoactive substance-induced sleep disorder', 'F19.182')
, ('Other psychoactive substance abuse with other psychoactive substance-induced disorder', 'F19.188')
, ('Other psychoactive substance abuse with unspecified psychoactive substance-induced disorder', 'F19.19')
, ('Other psychoactive substance dependence', 'F19.2')
, ('Other psychoactive substance dependence, uncomplicated', 'F19.20')
, ('Other psychoactive substance dependence with intoxication', 'F19.22')
, ('Other psychoactive substance dependence with intoxication, uncomplicated', 'F19.220')
, ('Other psychoactive substance dependence with intoxication delirium', 'F19.221')
, ('Other psychoactive substance dependence with intoxication with perceptual disturbance', 'F19.222')
, ('Other psychoactive substance dependence with intoxication, unspecified', 'F19.229')
, ('Other psychoactive substance dependence with withdrawal', 'F19.23')
, ('Other psychoactive substance dependence with withdrawal, uncomplicated', 'F19.230')
, ('Other psychoactive substance dependence with withdrawal delirium', 'F19.231')
, ('Other psychoactive substance dependence with withdrawal with perceptual disturbance', 'F19.232')
, ('Other psychoactive substance dependence with withdrawal, unspecified', 'F19.239')
, ('Other psychoactive substance dependence with psychoactive substance-induced mood disorder', 'F19.24')
, ('Other psychoactive substance dependence with psychoactive substance-induced psychotic disorder', 'F19.25')
, ('Other psychoactive substance dependence with psychoactive substance-induced psychotic disorder with delusions', 'F19.250')
, ('Other psychoactive substance dependence with psychoactive substance-induced psychotic disorder with hallucinations', 'F19.251')
, ('Other psychoactive substance dependence with psychoactive substance-induced psychotic disorder, unspecified', 'F19.259')
, ('Other psychoactive substance dependence with psychoactive substance-induced persisting amnestic disorder', 'F19.26')
, ('Other psychoactive substance dependence with psychoactive substance-induced persisting dementia', 'F19.27')
, ('Other psychoactive substance dependence with other psychoactive substance-induced disorders', 'F19.28')
, ('Other psychoactive substance dependence with psychoactive substance-induced anxiety disorder', 'F19.280')
, ('Other psychoactive substance dependence with psychoactive substance-induced sexual dysfunction', 'F19.281')
, ('Other psychoactive substance dependence with psychoactive substance-induced sleep disorder', 'F19.282')
, ('Other psychoactive substance dependence with other psychoactive substance-induced disorder', 'F19.288')
, ('Other psychoactive substance dependence with unspecified psychoactive substance-induced disorder', 'F19.29')
, ('Other psychoactive substance use, unspecified', 'F19.9')
, ('Other psychoactive substance use, unspecified, uncomplicated', 'F19.90')
, ('Other psychoactive substance use, unspecified with intoxication', 'F19.92')
, ('Other psychoactive substance use, unspecified with intoxication, uncomplicated', 'F19.920')
, ('Other psychoactive substance use, unspecified with intoxication with delirium', 'F19.921')
, ('Other psychoactive substance use, unspecified with intoxication with perceptual disturbance', 'F19.922')
, ('Other psychoactive substance use, unspecified with intoxication, unspecified', 'F19.929')
, ('Other psychoactive substance use, unspecified with withdrawal', 'F19.93')
, ('Other psychoactive substance use, unspecified with withdrawal, uncomplicated', 'F19.930')
, ('Other psychoactive substance use, unspecified with withdrawal delirium', 'F19.931')
, ('Other psychoactive substance use, unspecified with withdrawal with perceptual disturbance', 'F19.932')
, ('Other psychoactive substance use, unspecified with withdrawal, unspecified', 'F19.939')
, ('Other psychoactive substance use, unspecified with psychoactive substance-induced mood disorder', 'F19.94')
, ('Other psychoactive substance use, unspecified with psychoactive substance-induced psychotic disorder', 'F19.95')
, ('Other psychoactive substance use, unspecified with psychoactive substance-induced psychotic disorder with delusions', 'F19.950')
, ('Other psychoactive substance use, unspecified with psychoactive substance-induced psychotic disorder with hallucinations', 'F19.951')
, ('Other psychoactive substance use, unspecified with psychoactive substance-induced psychotic disorder, unspecified', 'F19.959')
, ('Other psychoactive substance use, unspecified with psychoactive substance-induced persisting amnestic disorder', 'F19.96')
, ('Other psychoactive substance use, unspecified with psychoactive substance-induced persisting dementia', 'F19.97')
, ('Other psychoactive substance use, unspecified with other psychoactive substance-induced disorders', 'F19.98')
, ('Other psychoactive substance use, unspecified with psychoactive substance-induced anxiety disorder', 'F19.980')
, ('Other psychoactive substance use, unspecified with psychoactive substance-induced sexual dysfunction', 'F19.981')
, ('Other psychoactive substance use, unspecified with psychoactive substance-induced sleep disorder', 'F19.982')
, ('Other psychoactive substance use, unspecified with other psychoactive substance-induced disorder', 'F19.988')
, ('Other psychoactive substance use, unspecified with unspecified psychoactive substance-induced disorder', 'F19.99')
, ('Abuse of non-psychoactive substances', 'F55')
, ('Abuse of herbal or folk remedies', 'F55.1')
, ('Abuse of laxatives', 'F55.2')
, ('Alcohol related disorders', 'F10')
, ('Alcohol abuse', 'F10.1')
, ('Alcohol abuse, uncomplicated', 'F10.10')
, ('Alcohol abuse with intoxication', 'F10.12')
, ('Alcohol abuse with intoxication, uncomplicated', 'F10.120')
, ('Alcohol abuse with intoxication delirium', 'F10.121')
, ('Alcohol abuse with intoxication, unspecified', 'F10.129')
, ('Alcohol abuse, with withdrawal', 'F10.13')
, ('Alcohol abuse with withdrawal, uncomplicated', 'F10.130')
, ('Alcohol abuse with withdrawal delirium', 'F10.131')
, ('Alcohol abuse with withdrawal with perceptual disturbance', 'F10.132')
, ('Alcohol abuse with withdrawal, unspecified', 'F10.139')
, ('Alcohol abuse with alcohol-induced mood disorder', 'F10.14')
, ('Alcohol abuse with alcohol-induced psychotic disorder', 'F10.15')
, ('Alcohol abuse with alcohol-induced psychotic disorder with delusions', 'F10.150')
, ('Alcohol abuse with alcohol-induced psychotic disorder with hallucinations', 'F10.151')
, ('Alcohol abuse with alcohol-induced psychotic disorder, unspecified', 'F10.159')
, ('Alcohol abuse with other alcohol-induced disorders', 'F10.18')
, ('Alcohol abuse with alcohol-induced anxiety disorder', 'F10.180')
, ('Alcohol abuse with alcohol-induced sexual dysfunction', 'F10.181')
, ('Alcohol abuse with alcohol-induced sleep disorder', 'F10.182')
, ('Alcohol abuse with other alcohol-induced disorder', 'F10.188')
, ('Alcohol abuse with unspecified alcohol-induced disorder', 'F10.19')
, ('Alcohol abuse with unspecified alcohol-induced disorder', 'F10.19')
, ('Alcohol dependence', 'F10.2')
, ('Alcohol dependence, uncomplicated', 'F10.20')
, ('Alcohol dependence with intoxication', 'F10.22')
, ('Alcohol dependence with intoxication, uncomplicated', 'F10.220')
, ('Alcohol dependence with intoxication delirium', 'F10.221')
, ('Alcohol dependence with intoxication, unspecified', 'F10.229')
, ('Alcohol dependence with withdrawal', 'F10.23')
, ('Alcohol dependence with withdrawal, uncomplicated', 'F10.230')
, ('Alcohol dependence with withdrawal delirium', 'F10.231')
, ('Alcohol dependence with withdrawal with perceptual disturbance', 'F10.232')
, ('Alcohol dependence with withdrawal, unspecified', 'F10.239')
, ('Alcohol dependence with alcohol-induced mood disorder', 'F10.24')
, ('Alcohol dependence with alcohol-induced psychotic disorder', 'F10.25')
, ('Alcohol dependence with alcohol-induced psychotic disorder with delusions', 'F10.250')
, ('Alcohol dependence with alcohol-induced psychotic disorder with hallucinations', 'F10.251')
, ('Alcohol dependence with alcohol-induced psychotic disorder, unspecified', 'F10.259')
, ('Alcohol dependence with alcohol-induced persisting amnestic disorder', 'F10.26')
, ('Alcohol dependence with alcohol-induced persisting dementia', 'F10.27')
, ('Alcohol dependence with other alcohol-induced disorders', 'F10.28')
, ('Alcohol dependence with alcohol-induced anxiety disorder', 'F10.280')
, ('Alcohol dependence with alcohol-induced sexual dysfunction', 'F10.281')
, ('Alcohol dependence with alcohol-induced sleep disorder', 'F10.282')
, ('Alcohol dependence with other alcohol-induced disorder', 'F10.288')
, ('Alcohol dependence with unspecified alcohol-induced disorder', 'F10.29')
, ('Alcohol use, unspecified', 'F10.9')
, ('Alcohol use, unspecified, uncomplicated', 'F10.90')
, ('Alcohol use, unspecified with intoxication', 'F10.92')
, ('Alcohol use, unspecified with intoxication, uncomplicated', 'F10.920')
, ('Alcohol use, unspecified with intoxication delirium', 'F10.921')
, ('Alcohol use, unspecified with intoxication, unspecified', 'F10.929')
, ('Alcohol use, unspecified with withdrawal', 'F10.93')
, ('Alcohol use, unspecified with withdrawal, uncomplicated', 'F10.930')
, ('Alcohol use, unspecified with withdrawal delirium', 'F10.931')
, ('Alcohol use, unspecified with withdrawal with perceptual disturbance', 'F10.932')
, ('Alcohol use, unspecified with withdrawal, unspecified', 'F10.939')
, ('Alcohol use, unspecified with alcohol-induced mood disorder', 'F10.94')
, ('Alcohol use, unspecified with alcohol-induced psychotic disorder', 'F10.95')
, ('Alcohol use, unspecified with alcohol-induced psychotic disorder with delusions', 'F10.950')
, ('Alcohol use, unspecified with alcohol-induced psychotic disorder with hallucinations', 'F10.951')
, ('Alcohol use, unspecified with alcohol-induced psychotic disorder, unspecified', 'F10.959')
, ('Alcohol use, unspecified with alcohol-induced persisting amnestic disorder', 'F10.96')
, ('Alcohol use, unspecified with alcohol-induced persisting dementia', 'F10.97')
, ('Alcohol use, unspecified with other alcohol-induced disorders', 'F10.98')
, ('Alcohol use, unspecified with alcohol-induced anxiety disorder', 'F10.980')
, ('Alcohol use, unspecified with alcohol-induced sexual dysfunction', 'F10.981')
, ('Alcohol use, unspecified with alcohol-induced sleep disorder', 'F10.982')
, ('Alcohol use, unspecified with other alcohol-induced disorder', 'F10.988')
, ('Alcohol use, unspecified with unspecified alcohol-induced disorder', 'F10.99')
, ('Opioid related disorders', 'F11')
, ('Opioid abuse', 'F11.1')
, ('Opioid abuse, uncomplicated', 'F11.10')
, ('Opioid abuse with intoxication', 'F11.12')
, ('Opioid abuse with intoxication, uncomplicated', 'F11.120')
, ('Opioid abuse with intoxication delirium', 'F11.121')
, ('Opioid abuse with intoxication with perceptual disturbance', 'F11.122')
, ('Opioid abuse with intoxication, unspecified', 'F11.129')
, ('Opioid abuse with withdrawal', 'F11.13')
, ('Opioid abuse with opioid-induced mood disorder', 'F11.14')
, ('Opioid abuse with opioid-induced psychotic disorder', 'F11.15')
, ('Opioid abuse with opioid-induced psychotic disorder with delusions', 'F11.150')
, ('Opioid abuse with opioid-induced psychotic disorder with hallucinations', 'F11.151')
, ('Opioid abuse with opioid-induced psychotic disorder, unspecified', 'F11.159')
, ('Opioid abuse with other opioid-induced disorder', 'F11.18')
, ('Opioid abuse with opioid-induced sexual dysfunction', 'F11.181')
, ('Opioid abuse with opioid-induced sleep disorder', 'F11.182')
, ('Opioid abuse with other opioid-induced disorder', 'F11.188')
, ('Opioid abuse with unspecified opioid-induced disorder', 'F11.19')
, ('Opioid dependence', 'F11.2')
, ('Opioid dependence, uncomplicated', 'F11.20')
, ('Opioid dependence with intoxication', 'F11.22')
, ('Opioid dependence with intoxication, uncomplicated', 'F11.220')
, ('Opioid dependence with intoxication delirium', 'F11.221')
, ('Opioid dependence with intoxication with perceptual disturbance', 'F11.222')
, ('Opioid dependence with intoxication, unspecified', 'F11.229')
, ('Opioid dependence with withdrawal', 'F11.23')
, ('Opioid dependence with opioid-induced mood disorder', 'F11.24')
, ('Opioid dependence with opioid-induced psychotic disorder', 'F11.25')
, ('Opioid dependence with opioid-induced psychotic disorder with delusions', 'F11.250')
, ('Opioid dependence with opioid-induced psychotic disorder with hallucinations', 'F11.251')
, ('Opioid dependence with opioid-induced psychotic disorder, unspecified', 'F11.259')
, ('Opioid dependence with other opioid-induced disorder', 'F11.28')
, ('Opioid dependence with opioid-induced sexual dysfunction', 'F11.281')
, ('Opioid dependence with opioid-induced sleep disorder', 'F11.282')
, ('Opioid dependence with other opioid-induced disorder', 'F11.288')
, ('Opioid dependence with unspecified opioid-induced disorder', 'F11.29')
, ('Opioid use, unspecified', 'F11.9')
, ('Opioid use, unspecified, uncomplicated', 'F11.90')
, ('Opioid use, unspecified with intoxication', 'F11.92')
, ('Opioid use, unspecified with intoxication, uncomplicated', 'F11.920')
, ('Opioid use, unspecified with intoxication delirium', 'F11.921')
, ('Opioid use, unspecified with intoxication with perceptual disturbance', 'F11.922')
, ('Opioid use, unspecified with intoxication, unspecified', 'F11.929')
, ('Opioid use, unspecified with withdrawal', 'F11.93')
, ('Opioid use, unspecified with opioid-induced mood disorder', 'F11.94')
, ('Opioid use, unspecified with opioid-induced psychotic disorder', 'F11.95')
, ('Opioid use, unspecified with opioid-induced psychotic disorder with delusions', 'F11.950')
, ('Opioid use, unspecified with opioid-induced psychotic disorder with hallucinations', 'F11.951')
, ('Opioid use, unspecified with opioid-induced psychotic disorder, unspecified', 'F11.959')
, ('Opioid use, unspecified with other specified opioid-induced disorder', 'F11.98')
, ('Opioid use, unspecified with opioid-induced sexual dysfunction', 'F11.981')
, ('Opioid use, unspecified with other opioid-induced disorder', 'F11.988')
, ('Opioid use, unspecified with unspecified opioid-induced disorder', 'F11.99')
, ('Cannabis related disorders', 'F12')
, ('Cannabis abuse', 'F12.1')
, ('Cannabis abuse, uncomplicated', 'F12.10')
, ('Cannabis abuse with intoxication', 'F12.12')
, ('Cannabis abuse with intoxication, uncomplicated', 'F12.120')
, ('Cannabis abuse with intoxication delirium', 'F12.121')
, ('Cannabis abuse with intoxication with perceptual disturbance', 'F12.122')
, ('Cannabis abuse with intoxication, unspecified', 'F12.129')
, ('Cannabis abuse with withdrawal', 'F12.13')
, ('Cannabis abuse with psychotic disorder', 'F12.15')
, ('Cannabis abuse with psychotic disorder with delusions', 'F12.150')
, ('Cannabis abuse with psychotic disorder with hallucinations', 'F12.151')
, ('Cannabis abuse with psychotic disorder, unspecified', 'F12.159')
, ('Cannabis abuse with other cannabis-induced disorder', 'F12.18')
, ('Cannabis abuse with cannabis-induced anxiety disorder', 'F12.180')
, ('Cannabis abuse with other cannabis-induced disorder', 'F12.188')
, ('Cannabis abuse with unspecified cannabis-induced disorder', 'F12.19')
, ('Cannabis dependence', 'F12.2')
, ('Cannabis dependence, uncomplicated', 'F12.20')
, ('Cannabis dependence with intoxication', 'F12.22')
, ('Cannabis dependence with intoxication, uncomplicated', 'F12.220')
, ('Cannabis dependence with intoxication delirium', 'F12.221')
, ('Cannabis dependence with intoxication with perceptual disturbance', 'F12.222')
, ('Cannabis dependence with intoxication, unspecified', 'F12.229')
, ('Cannabis dependence with withdrawal', 'F12.23')
, ('Cannabis dependence with psychotic disorder', 'F12.25');
GO
